- name: change shell
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /usr/local/bin/zsh
- name: clone dotfiles
  git: repo=git@github.com:rtlechow/dotfiles.git dest=/Users/rtl force=no update=no
